### ISSUE TITLE
Illegal instruction in jctx_setjmp(x)

### ISSUE THREAD

**Issue by Cha465** [IBM/uDepot#7]
When I run udepot-test in bin/, I got Illegal instruction in jctx_setjmp(x); if I set #define jctx_longjmp(x) longjmp(&(x)->ctx_, 1), I got segentation fault instead. My GCC version is 11.3.0.

**Comment by nik-io** [comment]
I haven't looked at this for a while, and the project is not really being maintained.

Unfortunately GCC disallowed using __builtin_longjmp and __builtin_setjmp since after GCC 7.4 or so.

But you should be able to build in a docker container using the supplied Dockerfile (`make docker-build` should do that transparently but haven't tried it in a while). If you statically build then you should be able to use the resulting binary outside the container.

Another thing that could work (but I did not try it), is to use the longjmp and setjmp implementations shared at https://nullprogram.com/blog/2023/02/12/.

**Comment by Cha465** [comment]
Thanks, `make docker-build` works fine for me. However when I try `BUILD=PERFORMANCE BUILD_SPDK=1 make docker-build` I get 

warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
  CC [M]  /udepot/trt/external/dpdk/build/build/lib/librte_eal/linuxapp/kni/kni_misc.o
  CC [M]  /udepot/trt/external/dpdk/build/build/lib/librte_eal/linuxapp/kni/kni_net.o
gcc: error: unrecognized command line option '-mharden-sls=all'; did you mean '-mhard-float'?
gcc: error: unrecognized command line option '-mharden-sls=all'; did you mean '-mhard-float'?
gcc: error: unrecognized command line option '-fzero-call-used-regs=used-gpr'
scripts/Makefile.build:257: recipe for target '/udepot/trt/external/dpdk/build/build/lib/librte_eal/linuxapp/kni/kni_misc.o' failed
make[9]: *** [/udepot/trt/external/dpdk/build/build/lib/librte_eal/linuxapp/kni/kni_misc.o] Error 1
make[9]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command line option '-fzero-call-used-regs=used-gpr'
scripts/Makefile.build:257: recipe for target '/udepot/trt/external/dpdk/build/build/lib/librte_eal/linuxapp/kni/kni_net.o' failed

I realize this could be a matter of kernel version, but could I solve this problem without changing kernel version? Or does io_uring work just as well as spdk so I could use the default settings?

**Comment by nik-io** [comment]
Yes, this sounds like a kernel mismatch issue while building dpdk.

io_uring should perform well too, but depending on your setup spdk might be faster.

**Comment by Cha465** [comment]
I am using spdk now, but no namespace can be found after `./udepot-test -f PHAL2023005P400BGN -w 10000000 -t 20 --grain-size 4096 --val-size 3072 -u 7 --thin --zero-copy --force-destroy`
```
spawning scheduler on lcore=5 i=4
S3   :T4            t_main_bench() main task: enter
S0   :T0             thread_init() init done
S0   :T0    set_SpdkNamespaceStr() No SPDK namespaces found
src/uDepot/udepot-lsa.cc:91: register_local_region() failed to open PHAL2023005P400BGN rc=-1 errno=Invalid argument
src/uDepot/udepot-lsa.cc:173: init_local() register_local_region failed with -1.

test/uDepot/udepot-test.cc:817: t_main_bench() KV init failed with -1 (Unknown error -1)
```
Moreover, if I run trt/external/spdk/scripts.sh before running test, it will do weird things to my /user/bin and my system crashes.

**Comment by Cha465** [comment]
> I am using spdk now, but no namespace can be found after `./udepot-test -f PHAL2023005P400BGN -w 10000000 -t 20 --grain-size 4096 --val-size 3072 -u 7 --thin --zero-copy --force-destroy`
> 
> ```
> spawning scheduler on lcore=5 i=4
> S3   :T4            t_main_bench() main task: enter
> S0   :T0             thread_init() init done
> S0   :T0    set_SpdkNamespaceStr() No SPDK namespaces found
> src/uDepot/udepot-lsa.cc:91: register_local_region() failed to open PHAL2023005P400BGN rc=-1 errno=Invalid argument
> src/uDepot/udepot-lsa.cc:173: init_local() register_local_region failed with -1.
> 
> test/uDepot/udepot-test.cc:817: t_main_bench() KV init failed with -1 (Unknown error -1)
> ```
> 
> Moreover, if I run trt/external/spdk/scripts.sh before running test, it will do weird things to my /user/bin and my system crashes.

Turned out that changing to newer spdk scripts(v 21.x) solves this.
